# Generated by Django 5.0.1 on 2024-01-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_failure',
            field=models.BooleanField(default=False),
        ),
    ]
