# Generated by Django 5.0.1 on 2024-01-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0002_video_is_failure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='is_failure',
        ),
        migrations.AddField(
            model_name='video',
            name='failure_type',
            field=models.CharField(choices=[('no_issue', 'No Issue'), ('technical_issue', 'Technical Issue'), ('content_issue', 'Content Issue')], default='no_issue', max_length=20),
        ),
    ]
