# Generated by Django 5.0.1 on 2024-01-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0003_remove_video_is_failure_video_failure_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='failure_type',
        ),
    ]
